spring.application.name=WalletWise
# H2 Database beallitasok
spring.datasource.url=jdbc:h2:mem:walletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# H2 Konzolt elerhetjuk a bongeszobol
spring.h2.console.enabled=true
# SQL logolas a konzolra (segit a hibakeresesben)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
